# Add this layer's configuration and recipes to the build.
BBPATH .= ":${LAYERDIR}"
BBFILES += "${LAYERDIR}/recipes-*/*/*.bb \
            ${LAYERDIR}/recipes-*/*/*.bbappend"

BBFILE_COLLECTIONS += "pivision"
BBFILE_PATTERN_pivision = "^${LAYERDIR}/"
BBFILE_PRIORITY_pivision = "10"

LAYERDEPENDS_pivision = "core raspberrypi qt6-layer openembedded-layer"
LAYERSERIES_COMPAT_pivision = "scarthgap"
