# Add this layer's configuration and recipes to the build.
BBPATH .= ":${LAYERDIR}"
BBFILES += "${LAYERDIR}/recipes-*/*/*.bb \
            ${LAYERDIR}/recipes-*/*/*.bbappend"

# bbappends for layers that only some targets use.
BBFILES_DYNAMIC += "raspberrypi:${LAYERDIR}/dynamic-layers/raspberrypi/*/*/*.bbappend"

BBFILE_COLLECTIONS += "pivision"
BBFILE_PATTERN_pivision = "^${LAYERDIR}/"
BBFILE_PRIORITY_pivision = "10"

LAYERDEPENDS_pivision = "core qt6-layer openembedded-layer meta-python"
LAYERSERIES_COMPAT_pivision = "scarthgap"

